spring:
  application:
    # 服务名称尽量用-,不要用_,不要用特殊字符
    name: user-center
  datasource:
    url: jdbc:mysql://112.74.99.22:3306/content_center
    hikari:
      username: root
      password: cyh.99
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 112.74.99.22:8848


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8082